
import React from 'react';

export const TermsOfService: React.FC = () => {
  const lastUpdated = new Date().toLocaleDateString();

  return (
    <div className="max-w-4xl mx-auto px-6 py-12 font-sans text-gray-800 bg-white rounded-3xl shadow-sm border-2 border-pd-lightest animate-in fade-in slide-in-from-bottom-4 duration-500">
      <header className="mb-12 border-b border-gray-200 pb-8">
        <h1 className="text-4xl font-black mb-2 tracking-tight text-pd-darkblue">Terms of Service</h1>
        <p className="text-gray-500">Last Updated: {lastUpdated}</p>
        <p className="mt-4 text-lg font-medium text-pd-teal">
          Rules of the Pack. Please read these carefully before using our platform.
        </p>
      </header>

      <section className="space-y-8">
        <div className="policy-section">
          <h2 className="text-2xl font-bold mb-3 text-pd-darkblue">1. Acceptance of Terms</h2>
          <p className="text-pd-slate leading-relaxed">
            By accessing the website or services provided by <strong>Partners Animal Institute, Inc.</strong> ("Company"), you agree to be bound by these Terms.
          </p>
        </div>

        <div className="policy-section bg-rose-50 p-6 rounded-2xl border-2 border-rose-100">
          <h2 className="text-2xl font-bold mb-3 text-rose-900">2. Assumption of Risk (Dog Training)</h2>
          <p className="mb-4 text-rose-800 font-medium">
            This section is critical. Working with animals involves inherent risks.
          </p>
          <ul className="list-disc pl-5 space-y-2 text-rose-900 marker:text-rose-500">
            <li><strong>Physical Risk:</strong> You acknowledge that dog training involves physical activity and interaction with animals that may be unpredictable. You voluntarily assume all risks of injury, bites, or damages.</li>
            <li><strong>AI Advice Disclaimer:</strong> Insights generated by our AI are for informational purposes only. They do not constitute veterinary advice or a professional behavioral diagnosis. <strong>Always consult a professional trainer or vet for aggression or anxiety issues.</strong></li>
            <li><strong>Release of Liability:</strong> You hereby release Partners Animal Institute, Inc. from any liability for injuries or damages arising from your use of our training suggestions.</li>
          </ul>
        </div>

        <div className="policy-section">
          <h2 className="text-2xl font-bold mb-3 text-pd-darkblue">3. Intellectual Property (The "Vibe" Clause)</h2>
          <p className="mb-2 text-pd-slate leading-relaxed">
            The design, code, "vibe," and user interface of this application are the exclusive property of Partners Animal Institute, Inc.
          </p>
          <p className="text-pd-slate leading-relaxed">
            <strong>No Scraping:</strong> You agree not to use automated tools (scrapers, spiders) to copy our content or UI, nor to use our data to train third-party AI models without our express written permission.
          </p>
        </div>

        <div className="policy-section">
          <h2 className="text-2xl font-bold mb-3 text-pd-darkblue">4. Data License</h2>
          <p className="text-pd-slate mb-2">
            You retain ownership of the photos and logs you upload. However, by uploading them, you grant us a license to use this data to:
          </p>
          <ul className="list-disc pl-5 mt-2 text-pd-slate marker:text-pd-teal">
            <li>Provide the service to you.</li>
            <li>Train and improve our internal AI models (using anonymized data).</li>
            <li>Market our success stories (only with your explicit permission).</li>
          </ul>
        </div>

        <div className="policy-section">
          <h2 className="text-2xl font-bold mb-3 text-pd-darkblue">5. Dispute Resolution</h2>
          <p className="text-pd-slate leading-relaxed">
            <strong>Binding Arbitration:</strong> Any dispute arising from these Terms shall be resolved through binding arbitration in <strong>Maricopa County, Arizona</strong>. You waive your right to a jury trial or to participate in a class action lawsuit.
          </p>
        </div>

        <div className="policy-section">
          <h2 className="text-2xl font-bold mb-3 text-pd-darkblue">6. Governing Law</h2>
          <p className="text-pd-slate leading-relaxed">
            These Terms shall be governed by the laws of the <strong>State of Arizona</strong>, without regard to its conflict of law provisions.
          </p>
        </div>

        <div className="policy-section">
          <h2 className="text-2xl font-bold mb-3 text-pd-darkblue">7. Contact Information</h2>
          <address className="not-italic text-pd-slate border-l-4 border-pd-yellow pl-4 py-2">
            Partners Animal Institute, Inc.<br />
            123 Training Way<br />
            Scottsdale, AZ 85255<br />
            support@partnersdogs.com
          </address>
        </div>
      </section>
    </div>
  );
};
